{% set name = "ecbdata" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ecbdata-{{ version }}.tar.gz
  sha256: 63611b45096acee369a3eb152a0794144b9925b4094aeb81f38c565ee946aeb2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests
    - pandas

test:
  imports:
    - ecbdata
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/LucaMingarelli/ecbdata
  summary: 'The ecbdata API allows for easy querying of data from the ECB Data Portal: https://data.ecb.europa.eu/help/data/overview.'
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - adament
